version: '3.4'

services:
  pedidosbtg.messaging:
    image: ${DOCKER_REGISTRY-}pedidosbtgmessaging
    build:
      context: .
      dockerfile: PedidosBTG.Messaging/Dockerfile

  pedidosbtg.core:
    image: ${DOCKER_REGISTRY-}pedidosbtgcore
    build:
      context: .
      dockerfile: PedidosBTG.Core/Dockerfile
      
  pedidosbtg.data:
    image: ${DOCKER_REGISTRY-}pedidosbtgdata
    build:
      context: .
      dockerfile: PedidosBTG.Data/Dockerfile

  pedidosbtg.restapi:
    image: ${DOCKER_REGISTRY-}pedidosbtgrestapi
    build:
      context: .
      dockerfile: PedidosBTG.RestApi/Dockerfile

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"